In [29]:
print("Working with NumPy")

Working with NumPy


In [30]:
#numpy - Numerical Python. Mathematic & Scientific calculations , multi-dimensional array
import numpy as np

In [35]:
n1=np.array([1,10])
print(n1)
type(n1)

[ 1 10]


numpy.ndarray

In [37]:
n2=np.array([[1,10],[10,1]])
print(n2)
type(n2)

[[ 1 10]
 [10  1]]


numpy.ndarray

In [38]:
n3=np.zeros([10,10])
print(n3)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [53]:
n3=np.full([10,10],10)
print(n3)
n3.shape

[[10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]]


(10, 10)

In [42]:
#last digit is exclusive
n4=np.arange(10,20)
print(n4)

[10 11 12 13 14 15 16 17 18 19]


In [45]:
#last digit is exclusive
n5=np.arange(10,20,3)
print(n5)

[10 13 16 19]


In [52]:
ranArr=np.random.randint(1000,1900,10)
print(ranArr)

[1764 1126 1836 1073 1226 1219 1810 1793 1527 1375]


In [62]:
n7 = np.array([[1,3,4],[4,3,1]])
print(n7)
n7.shape

n7.shape = (3,2)
print(n7)

[[1 3 4]
 [4 3 1]]
[[1 3]
 [4 4]
 [3 1]]


In [63]:
a = np.array([10,30])
b = np.array([20,40])

In [64]:
#sum all the numbers
np.sum([a,b])

100

In [65]:
#sum vertical
np.sum([a,b],axis=0)

array([30, 70])

In [66]:
#sum horizontal
np.sum([a,b],axis=1)

array([40, 60])

In [67]:
#Combine 2 arrays Vertical
np.vstack([a,b])

array([[10, 30],
       [20, 40]])

In [68]:
#combine 2 arrays Horizontal
np.hstack([a,b])

array([10, 30, 20, 40])

In [69]:
#combine 2 arrays using columns. Basically Inverting the matrix
np.column_stack([a,b])

array([[10, 20],
       [30, 40]])